/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AttendenceTable: typeof import('./src/components/features/AttendenceTable.vue')['default']
    ClinicInformationCard: typeof import('./src/components/features/ClinicInformationCard.vue')['default']
    DropWithAvatar: typeof import('./src/components/features/DropWithAvatar.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    LeftMenu: typeof import('./src/components/layout/LeftMenu.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    MenuItem: typeof import('./src/components/features/MenuItem.vue')['default']
    PageTop: typeof import('./src/components/layout/PageTop.vue')['default']
    PatientInfoCard: typeof import('./src/components/features/PatientInfoCard.vue')['default']
    PatientStatsSections: typeof import('./src/components/features/PatientStatsSections.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./src/components/features/StatsCard.vue')['default']
    StatsItem: typeof import('./src/components/features/StatsItem.vue')['default']
    StatusCard: typeof import('./src/components/features/StatusCard.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
  }
}
